// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOeU-R1cn-wFb1QJ3kiZCS8_9N40V7k9M',
    appId: '1:155421108316:web:ad3c62dd6bf9aaaaeade99',
    messagingSenderId: '155421108316',
    projectId: 'fitplan-ab9f0',
    authDomain: 'fitplan-ab9f0.firebaseapp.com',
    storageBucket: 'fitplan-ab9f0.appspot.com',
    measurementId: 'G-0MPGYV6ENW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ2r6-WdLiFRaSh4OV6xFbsdajGSisK1U',
    appId: '1:155421108316:android:fecda8640f95000deade99',
    messagingSenderId: '155421108316',
    projectId: 'fitplan-ab9f0',
    storageBucket: 'fitplan-ab9f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkymQ_xYLB-17T5n8690jbQTFqUcZ2DE',
    appId: '1:155421108316:ios:61a1e6532b9a99cceade99',
    messagingSenderId: '155421108316',
    projectId: 'fitplan-ab9f0',
    storageBucket: 'fitplan-ab9f0.appspot.com',
    iosBundleId: 'com.example.fitplanv1',
  );
}
